on:
  push:
  pull_request:

name: lake build

jobs:
  build:
    name: ${{ matrix.name }}
    runs-on: ${{ matrix.os }}
    defaults:
      run:
        shell: ${{ matrix.shell || 'sh' }}
    strategy:
      matrix:
        include:
        - name: Build on Ubuntu
          os: ubuntu-latest
        - name: Build on macOS
          os: macos-latest
        - name: Build on Windows
          os: windows-latest
          shell: msys2 {0}
    steps:
      - name: Install MSYS2 (Windows)
        if: matrix.os == 'windows-latest'
        uses: msys2/setup-msys2@v2
        with:
          path-type: inherit
          install: curl unzip python

      - name: Install elan
        shell: bash
        run: |
          curl -sSfLO https://raw.githubusercontent.com/leanprover/elan/master/elan-init.sh
          chmod +x elan-init.sh
          ./elan-init.sh -y --default-toolchain none
          echo "$HOME/.elan/bin" >> $GITHUB_PATH

      - uses: actions/checkout@v4

      - name: Update NPM (Windows)
        shell: bash
        if: matrix.os == 'windows-latest'
        # See https://github.com/nodejs/node/issues/52682
        run: cd widget/ && npm install npm

      - name: Get Cache
        run: lake exe cache get

      - name: Build package
        run: lake build Chess
